import type { SchemaDoc } from "../../types.js";

const now = new Date();

export const DEFAULT_SCHEMAS: SchemaDoc[] = [
  {
    typeId: "person",
    displayName: "Person",
    version: 1,
    fields: [
      { fieldId: "role", label: "Role / Title", dataType: "string", required: false },
      { fieldId: "department", label: "Department", dataType: "string", required: false },
      { fieldId: "reporting_to", label: "Reports To", dataType: "entity_ref", required: false },
      { fieldId: "trust_level", label: "Trust Level", dataType: "enum", required: false, enumValues: ["high", "medium", "low", "unknown"] },
      { fieldId: "notes", label: "Notes", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "works_with", label: "Works With", targetTypeId: "person", cardinality: "many" },
      { relationshipId: "owns", label: "Owns", targetTypeId: "project", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "org_unit",
    displayName: "Org Unit / Team",
    version: 1,
    fields: [
      { fieldId: "level", label: "Level", dataType: "enum", required: false, enumValues: ["company", "division", "department", "team", "squad"] },
      { fieldId: "parent_unit", label: "Parent Unit", dataType: "entity_ref", required: false },
      { fieldId: "head", label: "Head", dataType: "entity_ref", required: false },
      { fieldId: "mandate", label: "Mandate", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "has_member", label: "Has Member", targetTypeId: "person", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "project",
    displayName: "Project",
    version: 1,
    fields: [
      { fieldId: "status", label: "Status", dataType: "enum", required: false, enumValues: ["planning", "active", "blocked", "shipped", "cancelled"] },
      { fieldId: "owner", label: "Owner", dataType: "entity_ref", required: false },
      { fieldId: "priority", label: "Priority", dataType: "enum", required: false, enumValues: ["p0", "p1", "p2", "p3"] },
      { fieldId: "launch_date", label: "Launch Date", dataType: "date", required: false },
      { fieldId: "blockers", label: "Blockers", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "has_stakeholder", label: "Has Stakeholder", targetTypeId: "person", cardinality: "many" },
      { relationshipId: "depends_on", label: "Depends On", targetTypeId: "project", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "initiative",
    displayName: "Initiative",
    version: 1,
    fields: [
      { fieldId: "vision", label: "Vision", dataType: "text", required: false },
      { fieldId: "status", label: "Status", dataType: "enum", required: false, enumValues: ["ideation", "planning", "active", "complete", "cancelled"] },
      { fieldId: "type", label: "Type", dataType: "enum", required: false, enumValues: ["strategic", "tactical"] },
      { fieldId: "success_criteria", label: "Success Criteria", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "contains_project", label: "Contains Project", targetTypeId: "project", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "decision",
    displayName: "Decision",
    version: 1,
    fields: [
      { fieldId: "context", label: "Context", dataType: "text", required: false },
      { fieldId: "options_considered", label: "Options Considered", dataType: "text", required: false },
      { fieldId: "chosen", label: "Chosen Option", dataType: "string", required: false },
      { fieldId: "rationale", label: "Rationale", dataType: "text", required: false },
      { fieldId: "decided_by", label: "Decided By", dataType: "entity_ref", required: false },
      { fieldId: "decided_at", label: "Decided At", dataType: "date", required: false },
      { fieldId: "revisit_trigger", label: "Revisit Trigger", dataType: "string", required: false, description: "Condition under which to revisit this decision" },
    ],
    relationships: [
      { relationshipId: "affects_project", label: "Affects Project", targetTypeId: "project", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "experiment",
    displayName: "Experiment / A-B Test",
    version: 1,
    fields: [
      { fieldId: "hypothesis", label: "Hypothesis", dataType: "text", required: false },
      { fieldId: "metric", label: "Primary Metric", dataType: "string", required: false },
      { fieldId: "variant_description", label: "Variant Description", dataType: "text", required: false },
      { fieldId: "status", label: "Status", dataType: "enum", required: false, enumValues: ["planned", "running", "complete", "stopped"] },
      { fieldId: "result", label: "Result", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "belongs_to_project", label: "Belongs To Project", targetTypeId: "project", cardinality: "one" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "customer",
    displayName: "Customer / Account",
    version: 1,
    fields: [
      { fieldId: "tier", label: "Tier", dataType: "enum", required: false, enumValues: ["enterprise", "mid-market", "smb", "free"] },
      { fieldId: "industry", label: "Industry", dataType: "string", required: false },
      { fieldId: "champion", label: "Champion", dataType: "entity_ref", required: false },
      { fieldId: "arr", label: "ARR", dataType: "string", required: false },
      { fieldId: "use_case", label: "Use Case", dataType: "text", required: false },
      { fieldId: "health_status", label: "Health", dataType: "enum", required: false, enumValues: ["green", "yellow", "red", "churned"] },
      { fieldId: "last_contact", label: "Last Contact", dataType: "date", required: false },
    ],
    relationships: [
      { relationshipId: "has_contact", label: "Has Contact", targetTypeId: "person", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "situation",
    displayName: "Situation",
    version: 1,
    fields: [
      { fieldId: "category", label: "Category", dataType: "enum", required: false, enumValues: ["conflict", "negotiation", "risk", "opportunity", "dependency", "other"] },
      { fieldId: "status", label: "Status", dataType: "enum", required: false, enumValues: ["active", "resolved", "stalled", "watching"] },
      { fieldId: "summary", label: "Summary", dataType: "text", required: false },
      { fieldId: "outcome", label: "Outcome", dataType: "text", required: false },
      { fieldId: "start_date", label: "Start Date", dataType: "date", required: false },
      { fieldId: "end_date", label: "End Date", dataType: "date", required: false },
    ],
    relationships: [
      { relationshipId: "involves", label: "Involves", targetTypeId: "*", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "meeting",
    displayName: "Meeting",
    version: 1,
    fields: [
      { fieldId: "date", label: "Date", dataType: "date", required: false },
      { fieldId: "agenda", label: "Agenda", dataType: "text", required: false },
      { fieldId: "outcomes", label: "Outcomes", dataType: "text", required: false },
      { fieldId: "action_items", label: "Action Items", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "has_attendee", label: "Has Attendee", targetTypeId: "person", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "risk",
    displayName: "Risk",
    version: 1,
    fields: [
      { fieldId: "probability", label: "Probability", dataType: "enum", required: false, enumValues: ["low", "medium", "high"] },
      { fieldId: "impact", label: "Impact", dataType: "enum", required: false, enumValues: ["low", "medium", "high", "critical"] },
      { fieldId: "mitigation_plan", label: "Mitigation Plan", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "threatens", label: "Threatens", targetTypeId: "*", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
  {
    typeId: "reflection",
    displayName: "Reflection",
    version: 1,
    fields: [
      { fieldId: "category", label: "Category", dataType: "enum", required: false, enumValues: ["lesson", "pattern", "mistake", "win", "feedback"] },
      { fieldId: "key_insights", label: "Key Insights", dataType: "text", required: false },
      { fieldId: "triggers", label: "What triggered this", dataType: "text", required: false },
    ],
    relationships: [
      { relationshipId: "related_to", label: "Related To", targetTypeId: "*", cardinality: "many" },
    ],
    createdBy: "system",
    approvedAt: now,
    deprecated: false,
    createdAt: now,
  },
];
